version: '3'

networks:
  net:

services:
  web:
    container_name: nginx_test
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/public
    networks:
      - net

  cgi:
    container_name: php_test
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/php/php-conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src:/var/www
    networks:
      - net
